# Generated by Django 2.2.3 on 2019-07-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_code', models.IntegerField()),
                ('pone_number', models.IntegerField()),
                ('cell_number', models.IntegerField()),
                ('education_degree', models.CharField(max_length=50)),
            ],
        ),
    ]
