# Generated by Django 2.2.3 on 2019-07-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='DemographicInfo',
        ),
    ]
