# Generated by Django 2.2.3 on 2019-07-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0002_auto_20190728_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicinfo',
            name='cell_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demographicinfo',
            name='national_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demographicinfo',
            name='pone_number',
            field=models.CharField(max_length=100),
        ),
    ]
