# Generated by Django 2.2.3 on 2019-07-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0003_auto_20190728_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demographicinfo',
            old_name='pone_number',
            new_name='phone_number',
        ),
    ]
