# Generated by Django 2.2.3 on 2019-07-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0004_auto_20190728_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicinfo',
            name='cell_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demographicinfo',
            name='education_degree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demographicinfo',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demographicinfo',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demographicinfo',
            name='national_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demographicinfo',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
